#!/bin/bash

numrun=`ps -aux | grep "/home/pi/discordbot/discordstartup" | wc -l`

export parentmd5=`md5sum /home/pi/discordbot/index.js`

if [ $numrun -ge 2 ]
then
	echo "Already Running: $numrun"
else
	echo "Starting new process"
	/home/pi/discordbot/discordstartup &
fi
