#!/bin/bash

oldmd5=`echo "$parentmd5"`

node /home/pi/discordbot/index.js &

while true; do
	discordmd5=`md5sum /home/pi/discordbot/index.js`
	if [ "$discordmd5" != "$oldmd5" ];
	then
		echo "Changed"
		kill -9 `pidof node /home/pi/discordbot/index.js`
		node /home/pi/discordbot/index.js &
		export oldmd5=`echo "$discordmd5"`
	fi

	sleep 10

done
